Vagrant.configure("2") do |config|
  config.vm.box = "boomboxes/sandbox"
  config.vm.box_version = "1.0"

  config.vm.boot_timeout = 600
  config.winrm.transport = :plaintext
  config.vm.communicator = "winrm"
  config.winrm.basic_auth_only = true
  config.winrm.timeout = 100
  config.winrm.retry_limit = 20
  config.vm.network :private_network, ip: "192.168.56.101", gateway: "192.168.56.1", dns: "192.168.56.1"

  config.vm.provision "shell", path: "scripts/disable_winupdate.ps1", privileged: false
  config.vm.provision "shell", path: "scripts/disable_winfirewall.ps1", privileged: false
  config.vm.provision "shell", path: "scripts/disable_defender.ps1", privileged: false
  config.vm.provision "shell", path: "scripts/install_choco.ps1", privileged: false
  config.vm.provision "shell", path: "scripts/install_python.ps1", privileged: false
  config.vm.provision "shell", path: "scripts/install_pillow.ps1", privileged: false
  config.vm.provision "shell", path: "scripts/install_agent.ps1", privileged: false
  config.vm.provision "shell", path: "scripts/enable_rpc.ps1", privileged: false
  #config.vm.provision "shell", path: "scripts/fix_networking.ps1", privileged: false
  config.vm.provision "shell", path: "scripts/disable_defender.ps1", privileged: false
  config.vm.provision "shell", path: "scripts/disable_probing.ps1", privileged: false
  config.vm.provision "shell",
    run: "always",
    inline: "ROUTE change 0.0.0.0  MASK 0.0.0.0 192.168.56.1  METRIC 10"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider 'virtualbox' do |v, override|
    v.gui = false
    v.name = "cuckoo1"
    v.cpus = 2
    v.memory = 4096
    #v.default_nic_type = "82545EM"
    v.customize ["modifyvm", :id, "--vram", "32"]
    v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end
end
